version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:slim
    container_name: music-db
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - ./oracle-data:/opt/oracle/oradata